name: SLA
version: 1.5
date: 2018-07-25
description: |
    Computing with simple Lie algebras

authors:
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

maintainers:
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

GAP: ">=4.8"

needed-pkgs:
    - name: "quagroup"
      version: ">=1.8"
      url: "http://www.science.unitn.it/~degraaf/quagroup.html"

www: https://gap-packages.github.io/sla/
readme: README.md
packageinfo: https://gap-packages.github.io/sla/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sla/releases/download/v1.5/sla-1.5.tar.gz

abstract: |
    The package <span class="pkgname">SLA</span> contains                  functionality for working with simple Lie algebras,

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    simple Lie algebras, representation theory.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>dG18</span>]   <b class='BibAuthor'>de Graaf, W. A.</b>,
     <i class='BibTitle'>SLA, Computing with simple Lie algebras,
             Version 1.5</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/sla/">https://gap-packages.github.io/sla/</a></span>.
    </p>
    

bibtex: |
    @misc{ SLA1.5,
      author =           {de Graaf, W. A.},
      title =            {{SLA}, Computing with simple Lie algebras, {V}ersion 1.5},
      month =            {Jul},
      year =             {2018},
      note =             {Refereed GAP package},
      howpublished =     {\href {https://gap-packages.github.io/sla/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{sla/}}},
      keywords =         {simple Lie algebras; representation theory},
      printedkey =       {dG18}
    }

